steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/backend-api", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend-api"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "backend-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/backend-api"
      - "--region"
      - "asia-southeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "CLOUD_SQL_HOST=${_CLOUD_SQL_HOST},CLOUD_SQL_USER=${_CLOUD_SQL_USER},CLOUD_SQL_PASSWORD=${_CLOUD_SQL_PASSWORD},CLOUD_SQL_DATABASE=${_CLOUD_SQL_DATABASE},SECRET_KEY=${_SECRET_KEY}"

images:
  - "gcr.io/$PROJECT_ID/backend-api"
